//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
///			Copyright 2021 (C) Bruno Xavier B. Leite
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#pragma once

#include "MCS_MonoCore.h"
#include "MCS_MonoCall.h"
#include "MCS_Subsystem.h"
#include "MCS_MonoObject.h"
#include "MCS_MonoUtility.h"

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class ICORE {
public:
	static void Register() {
		// :: UnrealEngine.cs ::
		{
			CS_API("LogError",ICALL::API::LogError);
			CS_API("LogMessage",ICALL::API::LogMessage);
			CS_API("LogWarning",ICALL::API::LogWarning);
			CS_API("PrintMessage",ICALL::API::PrintMessage);
			//
			CS_API("IsNativeClassValid",ICALL::API::IsNativeClassValid);
			CS_API("IsNativeObjectValid",ICALL::API::IsNativeObjectValid);
			CS_API("DestroyNativeObject",ICALL::API::DestroyNativeObject);
		}
		// :: MagicNode.cs ::
		{
			CS_API("QuitGame",ICALL::API::QuitGame);
			//
			CS_API("IsEditor",ICALL::API::IsEditor);
			CS_API("IsShipping",ICALL::API::IsShipping);
			CS_API("IsStandalone",ICALL::API::IsStandalone);
			CS_API("IsDevelopment",ICALL::API::IsDevelopment);
			//
			CS_API("IsServer",ICALL::API::IsServer);
			CS_API("IsClient",ICALL::API::IsClient);
			CS_API("IsDedicatedServer",ICALL::API::IsDedicatedServer);
			//
			CS_API("IsGameThread",ICALL::API::QuitGame);
			CS_API("HasAuthority",ICALL::API::QuitGame);
			//
			//
			CS_API("GetNativeContext",ICALL::API::GetNativeContext);
			CS_API("DestroyNativeNode",ICALL::API::DestroyNativeNode);
			//
			CS_API("ConsoleCommand",ICALL::API::ConsoleCommand);
			CS_API("InvokeFunction",ICALL::API::InvokeFunction);
		}
		// :: FString.cs ::
		{
			CS_ICALL("Unreal.Core.Engine","FString_Append",ICALL::API::FString_Append);
			CS_ICALL("Unreal.Core.Engine","FString_Compare",ICALL::API::FString_Compare);
			CS_ICALL("Unreal.Core.Engine","FString_Contains",ICALL::API::FString_Contains);
			CS_ICALL("Unreal.Core.Engine","FString_Empty",ICALL::API::FString_Empty);
			CS_ICALL("Unreal.Core.Engine","FString_EndsWith",ICALL::API::FString_EndsWith);
			CS_ICALL("Unreal.Core.Engine","FString_Equals",ICALL::API::FString_Equals);
			CS_ICALL("Unreal.Core.Engine","FString_Find",ICALL::API::FString_Find);
			CS_ICALL("Unreal.Core.Engine","FString_FindChar",ICALL::API::FString_FindChar);
			CS_ICALL("Unreal.Core.Engine","FString_FromInt",ICALL::API::FString_FromInt);
			CS_ICALL("Unreal.Core.Engine","FString_InsertAt",ICALL::API::FString_InsertAt);
			CS_ICALL("Unreal.Core.Engine","FString_IsEmpty",ICALL::API::FString_IsEmpty);
			CS_ICALL("Unreal.Core.Engine","FString_IsNumeric",ICALL::API::FString_IsNumeric);
			CS_ICALL("Unreal.Core.Engine","FString_IsValidIndex",ICALL::API::FString_IsValidIndex);
			CS_ICALL("Unreal.Core.Engine","FString_Mid",ICALL::API::FString_Mid);
			CS_ICALL("Unreal.Core.Engine","FString_RemoveAt",ICALL::API::FString_RemoveAt);
			CS_ICALL("Unreal.Core.Engine","FString_RemoveFromEnd",ICALL::API::FString_RemoveFromEnd);
			CS_ICALL("Unreal.Core.Engine","FString_RemoveFromStart",ICALL::API::FString_RemoveFromStart);
			CS_ICALL("Unreal.Core.Engine","FString_Replace",ICALL::API::FString_Replace);
			CS_ICALL("Unreal.Core.Engine","FString_StartsWith",ICALL::API::FString_StartsWith);
			CS_ICALL("Unreal.Core.Engine","FString_ToLower",ICALL::API::FString_ToLower);
			CS_ICALL("Unreal.Core.Engine","FString_ToUpper",ICALL::API::FString_ToUpper);
			CS_ICALL("Unreal.Core.Engine","FString_TrimEnd",ICALL::API::FString_TrimEnd);
			CS_ICALL("Unreal.Core.Engine","FString_TrimStart",ICALL::API::FString_TrimStart);
			CS_ICALL("Unreal.Core.Engine","FString_TrimStartAndEnd",ICALL::API::FString_TrimStartAndEnd);
		}
		// :: FName.cs ::
		{
			CS_ICALL("Unreal.Core.Engine","FName_AppendString",ICALL::API::FName_AppendString);
			CS_ICALL("Unreal.Core.Engine","FName_IsEqual",ICALL::API::FName_IsEqual);
			CS_ICALL("Unreal.Core.Engine","FName_IsNone",ICALL::API::FName_IsNone);
			CS_ICALL("Unreal.Core.Engine","FName_IsValid",ICALL::API::FName_IsValid);
		}
		// :: FText.cs ::
		{
			CS_ICALL("Unreal.Core.Engine","FText_AsCultureInvariant",ICALL::API::FText_AsCultureInvariant);
			CS_ICALL("Unreal.Core.Engine","FText_AsCurrency",ICALL::API::FText_AsCurrency);
			CS_ICALL("Unreal.Core.Engine","FText_AsDate",ICALL::API::FText_AsDate);
			CS_ICALL("Unreal.Core.Engine","FText_AsNumber",ICALL::API::FText_AsNumber);
			CS_ICALL("Unreal.Core.Engine","FText_AsPercent",ICALL::API::FText_AsPercent);
			CS_ICALL("Unreal.Core.Engine","FText_ToLower",ICALL::API::FText_ToLower);
			CS_ICALL("Unreal.Core.Engine","FText_ToUpper",ICALL::API::FText_ToUpper);
			//
			CS_ICALL("Unreal.Core.Engine","FText_EqualTo",ICALL::API::FText_EqualTo);
			CS_ICALL("Unreal.Core.Engine","FText_IsEmpty",ICALL::API::FText_IsEmpty);
			CS_ICALL("Unreal.Core.Engine","FText_IsNumeric",ICALL::API::FText_IsNumeric);
		}
		// :: FColor.cs ::
		{
			CS_ICALL("Unreal.Core.Engine","FColor_FromHex",ICALL::API::FColor_FromHex);
			CS_ICALL("Unreal.Core.Engine","FColor_ToHex",ICALL::API::FColor_ToHex);
			CS_ICALL("Unreal.Core.Engine","FColor_IsEqual",ICALL::API::FColor_IsEqual);
		}
		// :: FVector2D.cs ::
		{
			CS_ICALL("Unreal.Core.Engine","FVector2D_ClampAxes",ICALL::API::FVector2D_ClampAxes);
			CS_ICALL("Unreal.Core.Engine","FVector2D_ContainsNaN",ICALL::API::FVector2D_ContainsNaN);
			CS_ICALL("Unreal.Core.Engine","FVector2D_CrossProduct",ICALL::API::FVector2D_CrossProduct);
			CS_ICALL("Unreal.Core.Engine","FVector2D_Distance",ICALL::API::FVector2D_Distance);
			CS_ICALL("Unreal.Core.Engine","FVector2D_DistSquared",ICALL::API::FVector2D_DistSquared);
			CS_ICALL("Unreal.Core.Engine","FVector2D_DotProduct",ICALL::API::FVector2D_DotProduct);
			CS_ICALL("Unreal.Core.Engine","FVector2D_Equals",ICALL::API::FVector2D_Equals);
			CS_ICALL("Unreal.Core.Engine","FVector2D_GetAbs",ICALL::API::FVector2D_GetAbs);
			CS_ICALL("Unreal.Core.Engine","FVector2D_GetAbsMax",ICALL::API::FVector2D_GetAbsMax);
			CS_ICALL("Unreal.Core.Engine","FVector2D_GetMax",ICALL::API::FVector2D_GetMax);
			CS_ICALL("Unreal.Core.Engine","FVector2D_GetMin",ICALL::API::FVector2D_GetMin);
			CS_ICALL("Unreal.Core.Engine","FVector2D_GetRotated",ICALL::API::FVector2D_GetRotated);
			CS_ICALL("Unreal.Core.Engine","FVector2D_GetSafeNormal",ICALL::API::FVector2D_GetSafeNormal);
			CS_ICALL("Unreal.Core.Engine","FVector2D_GetSignVector",ICALL::API::FVector2D_GetSignVector);
			CS_ICALL("Unreal.Core.Engine","FVector2D_IsNearlyZero",ICALL::API::FVector2D_IsNearlyZero);
			CS_ICALL("Unreal.Core.Engine","FVector2D_IsZero",ICALL::API::FVector2D_IsZero);
			CS_ICALL("Unreal.Core.Engine","FVector2D_Max",ICALL::API::FVector2D_Max);
			CS_ICALL("Unreal.Core.Engine","FVector2D_Min",ICALL::API::FVector2D_Min);
			CS_ICALL("Unreal.Core.Engine","FVector2D_Normalize",ICALL::API::FVector2D_Normalize);
			CS_ICALL("Unreal.Core.Engine","FVector2D_RoundToVector",ICALL::API::FVector2D_RoundToVector);
			CS_ICALL("Unreal.Core.Engine","FVector2D_Size",ICALL::API::FVector2D_Size);
			CS_ICALL("Unreal.Core.Engine","FVector2D_SizeSquared",ICALL::API::FVector2D_SizeSquared);
			CS_ICALL("Unreal.Core.Engine","FVector2D_SphericalToUnitCartesian",ICALL::API::FVector2D_SphericalToUnitCartesian);
			CS_ICALL("Unreal.Core.Engine","FVector2D_ToDirectionAndLength",ICALL::API::FVector2D_ToDirection);
		}
		// :: FVector3D.cs ::
		{
			CS_ICALL("Unreal.Core.Engine","FVector3D_AddBounded",ICALL::API::FVector3D_AddBounded);
			CS_ICALL("Unreal.Core.Engine","FVector3D_BoundToBox",ICALL::API::FVector3D_BoundToBox);
			CS_ICALL("Unreal.Core.Engine","FVector3D_BoundToCube",ICALL::API::FVector3D_BoundToCube);
			CS_ICALL("Unreal.Core.Engine","FVector3D_CosineAngle2D",ICALL::API::FVector3D_CosineAngle2D);
			CS_ICALL("Unreal.Core.Engine","FVector3D_CreateOrthonormalBasis",ICALL::API::FVector3D_CreateOrthonormalBasis);
			CS_ICALL("Unreal.Core.Engine","FVector3D_CrossProduct",ICALL::API::FVector3D_CrossProduct);
			CS_ICALL("Unreal.Core.Engine","FVector3D_DegreesToRadians",ICALL::API::FVector3D_DegreesToRadians);
			CS_ICALL("Unreal.Core.Engine","FVector3D_DistSquared",ICALL::API::FVector3D_DistSquared);
			CS_ICALL("Unreal.Core.Engine","FVector3D_GetAbs",ICALL::API::FVector3D_GetAbs);
			CS_ICALL("Unreal.Core.Engine","FVector3D_GetClampedToMaxSize",ICALL::API::FVector3D_GetClampedToMaxSize);
			CS_ICALL("Unreal.Core.Engine","FVector3D_GetClampedToSize",ICALL::API::FVector3D_GetClampedToSize);
			CS_ICALL("Unreal.Core.Engine","FVector3D_GetSafeNormal",ICALL::API::FVector3D_GetSafeNormal);
			CS_ICALL("Unreal.Core.Engine","FVector3D_GetUnsafeNormal",ICALL::API::FVector3D_GetUnsafeNormal);
			CS_ICALL("Unreal.Core.Engine","FVector3D_GetSignVector",ICALL::API::FVector3D_GetSignVector);
			CS_ICALL("Unreal.Core.Engine","FVector3D_GridSnap",ICALL::API::FVector3D_GridSnap);
			CS_ICALL("Unreal.Core.Engine","FVector3D_MirrorByVector",ICALL::API::FVector3D_MirrorByVector);
			CS_ICALL("Unreal.Core.Engine","FVector3D_Projection",ICALL::API::FVector3D_Projection);
			CS_ICALL("Unreal.Core.Engine","FVector3D_ProjectOnTo",ICALL::API::FVector3D_ProjectOnTo);
			CS_ICALL("Unreal.Core.Engine","FVector3D_ProjectOnToNormal",ICALL::API::FVector3D_ProjectOnToNormal);
			CS_ICALL("Unreal.Core.Engine","FVector3D_RadiansToDegrees",ICALL::API::FVector3D_RadiansToDegrees);
			CS_ICALL("Unreal.Core.Engine","FVector3D_Reciprocal",ICALL::API::FVector3D_Reciprocal);
			CS_ICALL("Unreal.Core.Engine","FVector3D_RotateAngleAxis",ICALL::API::FVector3D_RotateAngleAxis);
			//
			CS_ICALL("Unreal.Core.Engine","FVector3D_Rotation",ICALL::API::FVector3D_Rotation);
			//
			CS_ICALL("Unreal.Core.Engine","FVector3D_BoxPushOut",ICALL::API::FVector3D_BoxPushOut);
			CS_ICALL("Unreal.Core.Engine","FVector3D_Distance",ICALL::API::FVector3D_Distance);
			CS_ICALL("Unreal.Core.Engine","FVector3D_DotProduct",ICALL::API::FVector3D_DotProduct);
			CS_ICALL("Unreal.Core.Engine","FVector3D_GetAbsMax",ICALL::API::FVector3D_GetAbsMax);
			CS_ICALL("Unreal.Core.Engine","FVector3D_GetAbsMin",ICALL::API::FVector3D_GetAbsMin);
			CS_ICALL("Unreal.Core.Engine","FVector3D_GetMax",ICALL::API::FVector3D_GetMax);
			CS_ICALL("Unreal.Core.Engine","FVector3D_GetMin",ICALL::API::FVector3D_GetMin);
			CS_ICALL("Unreal.Core.Engine","FVector3D_HeadingAngle",ICALL::API::FVector3D_HeadingAngle);
			CS_ICALL("Unreal.Core.Engine","FVector3D_PointPlaneDist",ICALL::API::FVector3D_PointPlaneDist);
			CS_ICALL("Unreal.Core.Engine","FVector3D_Triple",ICALL::API::FVector3D_Triple);
			CS_ICALL("Unreal.Core.Engine","FVector3D_VectorPlaneProject",ICALL::API::FVector3D_VectorPlaneProject);
			//
			CS_ICALL("Unreal.Core.Engine","FVector3D_Coincident",ICALL::API::FVector3D_Coincident);
			CS_ICALL("Unreal.Core.Engine","FVector3D_ContainsNaN",ICALL::API::FVector3D_ContainsNaN);
			CS_ICALL("Unreal.Core.Engine","FVector3D_Coplanar",ICALL::API::FVector3D_Coplanar);
			CS_ICALL("Unreal.Core.Engine","FVector3D_Equals",ICALL::API::FVector3D_Equals);
			CS_ICALL("Unreal.Core.Engine","FVector3D_IsNearlyZero",ICALL::API::FVector3D_IsNearlyZero);
			CS_ICALL("Unreal.Core.Engine","FVector3D_IsNormalized",ICALL::API::FVector3D_IsNormalized);
			CS_ICALL("Unreal.Core.Engine","FVector3D_IsUniform",ICALL::API::FVector3D_IsUniform);
			CS_ICALL("Unreal.Core.Engine","FVector3D_IsUnit",ICALL::API::FVector3D_IsUnit);
			CS_ICALL("Unreal.Core.Engine","FVector3D_IsZero",ICALL::API::FVector3D_IsZero);
			CS_ICALL("Unreal.Core.Engine","FVector3D_Normalize",ICALL::API::FVector3D_Normalize);
			CS_ICALL("Unreal.Core.Engine","FVector3D_Orthogonal",ICALL::API::FVector3D_Orthogonal);
			CS_ICALL("Unreal.Core.Engine","FVector3D_Parallel",ICALL::API::FVector3D_Parallel);
			CS_ICALL("Unreal.Core.Engine","FVector3D_PointsAreNear",ICALL::API::FVector3D_PointsAreNear);
			CS_ICALL("Unreal.Core.Engine","FVector3D_PointsAreSame",ICALL::API::FVector3D_PointsAreSame);
		}
		// :: FRotator.cs ::
		{
			CS_ICALL("Unreal.Core.Engine","FRotator_Add",ICALL::API::FRotator_Add);
			CS_ICALL("Unreal.Core.Engine","FRotator_Clamp",ICALL::API::FRotator_Clamp);
			CS_ICALL("Unreal.Core.Engine","FRotator_GetDenormalized",ICALL::API::FRotator_GetDenormalized);
			CS_ICALL("Unreal.Core.Engine","FRotator_GetEquivalentRotator",ICALL::API::FRotator_GetEquivalentRotator);
			CS_ICALL("Unreal.Core.Engine","FRotator_GetInverse",ICALL::API::FRotator_GetInverse);
			CS_ICALL("Unreal.Core.Engine","FRotator_GetNormalized",ICALL::API::FRotator_GetNormalized);
			CS_ICALL("Unreal.Core.Engine","FRotator_GridSnap",ICALL::API::FRotator_GridSnap);
			CS_ICALL("Unreal.Core.Engine","FRotator_MakeFromEuler",ICALL::API::FRotator_MakeFromEuler);
			CS_ICALL("Unreal.Core.Engine","FRotator_Normalize",ICALL::API::FRotator_Normalize);
			//
			CS_ICALL("Unreal.Core.Engine","FRotator_GetManhattanDistance",ICALL::API::FRotator_GetManhattanDistance);
			CS_ICALL("Unreal.Core.Engine","FRotator_ClampAxis",ICALL::API::FRotator_ClampAxis);
			//
			CS_ICALL("Unreal.Core.Engine","FRotator_Euler",ICALL::API::FRotator_Euler);
			CS_ICALL("Unreal.Core.Engine","FRotator_RotateVector",ICALL::API::FRotator_RotateVector);
			CS_ICALL("Unreal.Core.Engine","FRotator_UnrotateVector",ICALL::API::FRotator_UnrotateVector);
			//
			CS_ICALL("Unreal.Core.Engine","FRotator_ContainsNaN",ICALL::API::FRotator_ContainsNaN);
			CS_ICALL("Unreal.Core.Engine","FRotator_Equals",ICALL::API::FRotator_Equals);
			CS_ICALL("Unreal.Core.Engine","FRotator_IsNearlyZero",ICALL::API::FRotator_IsNearlyZero);
			CS_ICALL("Unreal.Core.Engine","FRotator_IsZero",ICALL::API::FRotator_IsZero);
		}
		// :: FTransform.cs ::
		{
			CS_ICALL("Unreal.Core.Engine","FTransform_AddTranslations",ICALL::API::FTransform_AddTranslations);
			CS_ICALL("Unreal.Core.Engine","FTransform_Blend",ICALL::API::FTransform_Blend);
			CS_ICALL("Unreal.Core.Engine","FTransform_BlendWith",ICALL::API::FTransform_BlendWith);
			CS_ICALL("Unreal.Core.Engine","FTransform_CopyRotation",ICALL::API::FTransform_CopyRotation);
			CS_ICALL("Unreal.Core.Engine","FTransform_CopyScale3D",ICALL::API::FTransform_CopyScale3D);
			CS_ICALL("Unreal.Core.Engine","FTransform_CopyTranslation",ICALL::API::FTransform_CopyTranslation);
			CS_ICALL("Unreal.Core.Engine","FTransform_CopyTranslationAndScale3D",ICALL::API::FTransform_CopyTranslationAndScale3D);
			CS_ICALL("Unreal.Core.Engine","FTransform_GetRelativeTransform",ICALL::API::FTransform_GetRelativeTransform);
			CS_ICALL("Unreal.Core.Engine","FTransform_GetRelativeTransformReverse",ICALL::API::FTransform_GetRelativeTransformReverse);
			CS_ICALL("Unreal.Core.Engine","FTransform_GetScaled",ICALL::API::FTransform_GetScaled);
			CS_ICALL("Unreal.Core.Engine","FTransform_Inverse",ICALL::API::FTransform_Inverse);
			CS_ICALL("Unreal.Core.Engine","FTransform_Multiply",ICALL::API::FTransform_Multiply);
			CS_ICALL("Unreal.Core.Engine","FTransform_NormalizeRotation",ICALL::API::FTransform_NormalizeRotation);
			//
			CS_ICALL("Unreal.Core.Engine","FTransform_GetTranslation",ICALL::API::FTransform_GetTranslation);
			CS_ICALL("Unreal.Core.Engine","FTransform_GetRotation",ICALL::API::FTransform_GetRotation);
			CS_ICALL("Unreal.Core.Engine","FTransform_GetScale3D",ICALL::API::FTransform_GetScale3D);
			//
			CS_ICALL("Unreal.Core.Engine","FTransform_GetDeterminant",ICALL::API::FTransform_GetDeterminant);
			CS_ICALL("Unreal.Core.Engine","FTransform_GetMaximumAxisScale",ICALL::API::FTransform_GetMaximumAxisScale);
			CS_ICALL("Unreal.Core.Engine","FTransform_GetMinimumAxisScale",ICALL::API::FTransform_GetMinimumAxisScale);
			//
			CS_ICALL("Unreal.Core.Engine","FTransform_AnyHasNegativeScale",ICALL::API::FTransform_AnyHasNegativeScale);
			CS_ICALL("Unreal.Core.Engine","FTransform_AreRotationsEqual",ICALL::API::FTransform_AreRotationsEqual);
			CS_ICALL("Unreal.Core.Engine","FTransform_AreScale3DsEqual",ICALL::API::FTransform_AreScale3DsEqual);
			CS_ICALL("Unreal.Core.Engine","FTransform_AreTranslationsEqual",ICALL::API::FTransform_AreTranslationsEqual);
			CS_ICALL("Unreal.Core.Engine","FTransform_ContainsNaN",ICALL::API::FTransform_ContainsNaN);
			CS_ICALL("Unreal.Core.Engine","FTransform_Equals",ICALL::API::FTransform_Equals);
			CS_ICALL("Unreal.Core.Engine","FTransform_EqualsNoScale",ICALL::API::FTransform_EqualsNoScale);
			CS_ICALL("Unreal.Core.Engine","FTransform_IsRotationNormalized",ICALL::API::FTransform_IsRotationNormalized);
			CS_ICALL("Unreal.Core.Engine","FTransform_IsValid",ICALL::API::FTransform_IsValid);
			CS_ICALL("Unreal.Core.Engine","FTransform_RotationEquals",ICALL::API::FTransform_RotationEquals);
			CS_ICALL("Unreal.Core.Engine","FTransform_Scale3DEquals",ICALL::API::FTransform_Scale3DEquals);
			CS_ICALL("Unreal.Core.Engine","FTransform_TranslationEquals",ICALL::API::FTransform_TranslationEquals);
		}
		// :: FClass.cs ::
		{
			CS_ICALL("Unreal.Core.Engine","FClassPtr_IsStale",ICALL::API::FClassPtr_IsStale);
			CS_ICALL("Unreal.Core.Engine","FClassPtr_IsValid",ICALL::API::FClassPtr_IsValid);
			CS_ICALL("Unreal.Core.Engine","FClassPtr_IsChildOf",ICALL::API::FClassPtr_IsChildOf);
			//
			CS_ICALL("Unreal.Core.Engine","FClassPtr_GetName",ICALL::API::FClassPtr_GetName);
			CS_ICALL("Unreal.Core.Engine","FClassPtr_GetFullPath",ICALL::API::FClassPtr_GetFullPath);
		}
		// :: FObject.cs ::
		{
			CS_ICALL("Unreal.Core.Engine","FObjectPtr_IsA",ICALL::API::FObjectPtr_IsA);
			CS_ICALL("Unreal.Core.Engine","FObjectPtr_IsStale",ICALL::API::FObjectPtr_IsStale);
			CS_ICALL("Unreal.Core.Engine","FObjectPtr_IsValid",ICALL::API::FObjectPtr_IsValid);
			//
			CS_ICALL("Unreal.Core.Engine","FObjectPtr_GetName",ICALL::API::FObjectPtr_GetName);
			CS_ICALL("Unreal.Core.Engine","FObjectPtr_GetFullPath",ICALL::API::FObjectPtr_GetFullPath);
			//
			CS_ICALL("Unreal.Core.Engine","FObjectPtr_GetClass",ICALL::API::FObjectPtr_GetClass);
			//
			CS_ICALL("Unreal.Core.Engine","FObjectPtr_InvokeFunction",ICALL::API::FObjectPtr_InvokeFunction);
		}
		// :: FActor.cs ::
		{
			CS_ICALL("Unreal.Core.Engine","FActorPtr_IsA",ICALL::API::FActorPtr_IsA);
			CS_ICALL("Unreal.Core.Engine","FActorPtr_IsStale",ICALL::API::FActorPtr_IsStale);
			CS_ICALL("Unreal.Core.Engine","FActorPtr_IsValid",ICALL::API::FActorPtr_IsValid);
			//
			CS_ICALL("Unreal.Core.Engine","FObjectPtr_GetName",ICALL::API::FActorPtr_GetName);
			CS_ICALL("Unreal.Core.Engine","FObjectPtr_GetFullPath",ICALL::API::FActorPtr_GetFullPath);
			//
			CS_ICALL("Unreal.Core.Engine","FActorPtr_GetClass",ICALL::API::FActorPtr_GetClass);
			//
			CS_ICALL("Unreal.Core.Engine","FActorPtr_InvokeFunction",ICALL::API::FActorPtr_InvokeFunction);
		}
		// :: FComponent.cs ::
		{
			CS_ICALL("Unreal.Core.Engine","FComponentPtr_IsA",ICALL::API::FComponentPtr_IsA);
			CS_ICALL("Unreal.Core.Engine","FComponentPtr_IsStale",ICALL::API::FComponentPtr_IsStale);
			CS_ICALL("Unreal.Core.Engine","FComponentPtr_IsValid",ICALL::API::FComponentPtr_IsValid);
			//
			CS_ICALL("Unreal.Core.Engine","FObjectPtr_GetName",ICALL::API::FComponentPtr_GetName);
			CS_ICALL("Unreal.Core.Engine","FObjectPtr_GetFullPath",ICALL::API::FComponentPtr_GetFullPath);
			//
			CS_ICALL("Unreal.Core.Engine","FObjectPtr_GetClass",ICALL::API::FComponentPtr_GetClass);
			//
			CS_ICALL("Unreal.Core.Engine","FComponentPtr_InvokeFunction",ICALL::API::FComponentPtr_InvokeFunction);
		}
		// :: TArray.cs ::
		{
			CS_ICALL("Unreal.Core.Engine","TArray_Append",ICALL::API::TArray_Append);
			CS_ICALL("Unreal.Core.Engine","TArray_Clear",ICALL::API::TArray_Clear);
			CS_ICALL("Unreal.Core.Engine","TArray_IsValidIndex",ICALL::API::TArray_IsValidIndex);
			CS_ICALL("Unreal.Core.Engine","TArray_Length",ICALL::API::TArray_Length);
			CS_ICALL("Unreal.Core.Engine","TArray_RemoveAt",ICALL::API::TArray_RemoveAt);
			CS_ICALL("Unreal.Core.Engine","TArray_Reverse",ICALL::API::TArray_Reverse);
			CS_ICALL("Unreal.Core.Engine","TArray_Shuffle",ICALL::API::TArray_Shuffle);
			CS_ICALL("Unreal.Core.Engine","TArray_Swap",ICALL::API::TArray_Swap);
			//
			CS_ICALL("Unreal.Core.Engine","TArray_Get_Bool",ICALL::API::TArray_Get_Bool);
			CS_ICALL("Unreal.Core.Engine","TArray_Get_Byte",ICALL::API::TArray_Get_Byte);
			CS_ICALL("Unreal.Core.Engine","TArray_Get_Int",ICALL::API::TArray_Get_Int);
			CS_ICALL("Unreal.Core.Engine","TArray_Get_Int64",ICALL::API::TArray_Get_Int64);
			CS_ICALL("Unreal.Core.Engine","TArray_Get_Float",ICALL::API::TArray_Get_Float);
			CS_ICALL("Unreal.Core.Engine","TArray_Get_String",ICALL::API::TArray_Get_String);
			CS_ICALL("Unreal.Core.Engine","TArray_Get_Name",ICALL::API::TArray_Get_Name);
			CS_ICALL("Unreal.Core.Engine","TArray_Get_Text",ICALL::API::TArray_Get_Text);
			CS_ICALL("Unreal.Core.Engine","TArray_Get_Color",ICALL::API::TArray_Get_Color);
			CS_ICALL("Unreal.Core.Engine","TArray_Get_Vector2D",ICALL::API::TArray_Get_Vector2D);
			CS_ICALL("Unreal.Core.Engine","TArray_Get_Vector3D",ICALL::API::TArray_Get_Vector3D);
			CS_ICALL("Unreal.Core.Engine","TArray_Get_Rotator",ICALL::API::TArray_Get_Rotator);
			CS_ICALL("Unreal.Core.Engine","TArray_Get_Transform",ICALL::API::TArray_Get_Transform);
			CS_ICALL("Unreal.Core.Engine","TArray_Get_Class",ICALL::API::TArray_Get_Class);
			CS_ICALL("Unreal.Core.Engine","TArray_Get_Object",ICALL::API::TArray_Get_Object);
			CS_ICALL("Unreal.Core.Engine","TArray_Get_Actor",ICALL::API::TArray_Get_Actor);
			CS_ICALL("Unreal.Core.Engine","TArray_Get_Component",ICALL::API::TArray_Get_Component);
			//
			CS_ICALL("Unreal.Core.Engine","TArray_Set_Bool",ICALL::API::TArray_Set_Bool);
			CS_ICALL("Unreal.Core.Engine","TArray_Set_Byte",ICALL::API::TArray_Set_Byte);
			CS_ICALL("Unreal.Core.Engine","TArray_Set_Int",ICALL::API::TArray_Set_Int);
			CS_ICALL("Unreal.Core.Engine","TArray_Set_Int64",ICALL::API::TArray_Set_Int64);
			CS_ICALL("Unreal.Core.Engine","TArray_Set_Float",ICALL::API::TArray_Set_Float);
			CS_ICALL("Unreal.Core.Engine","TArray_Set_String",ICALL::API::TArray_Set_String);
			CS_ICALL("Unreal.Core.Engine","TArray_Set_Name",ICALL::API::TArray_Set_Name);
			CS_ICALL("Unreal.Core.Engine","TArray_Set_Text",ICALL::API::TArray_Set_Text);
			CS_ICALL("Unreal.Core.Engine","TArray_Set_Color",ICALL::API::TArray_Set_Color);
			CS_ICALL("Unreal.Core.Engine","TArray_Set_Vector2D",ICALL::API::TArray_Set_Vector2D);
			CS_ICALL("Unreal.Core.Engine","TArray_Set_Vector3D",ICALL::API::TArray_Set_Vector3D);
			CS_ICALL("Unreal.Core.Engine","TArray_Set_Rotator",ICALL::API::TArray_Set_Rotator);
			CS_ICALL("Unreal.Core.Engine","TArray_Set_Transform",ICALL::API::TArray_Set_Transform);
			CS_ICALL("Unreal.Core.Engine","TArray_Set_Class",ICALL::API::TArray_Set_Class);
			CS_ICALL("Unreal.Core.Engine","TArray_Set_Object",ICALL::API::TArray_Set_Object);
			CS_ICALL("Unreal.Core.Engine","TArray_Set_Actor",ICALL::API::TArray_Set_Actor);
			CS_ICALL("Unreal.Core.Engine","TArray_Set_Component",ICALL::API::TArray_Set_Component);
			//
			CS_ICALL("Unreal.Core.Engine","TArray_Add_Bool",ICALL::API::TArray_Add_Bool);
			CS_ICALL("Unreal.Core.Engine","TArray_Add_Byte",ICALL::API::TArray_Add_Byte);
			CS_ICALL("Unreal.Core.Engine","TArray_Add_Int",ICALL::API::TArray_Add_Int);
			CS_ICALL("Unreal.Core.Engine","TArray_Add_Int64",ICALL::API::TArray_Add_Int64);
			CS_ICALL("Unreal.Core.Engine","TArray_Add_Float",ICALL::API::TArray_Add_Float);
			CS_ICALL("Unreal.Core.Engine","TArray_Add_String",ICALL::API::TArray_Add_String);
			CS_ICALL("Unreal.Core.Engine","TArray_Add_Name",ICALL::API::TArray_Add_Name);
			CS_ICALL("Unreal.Core.Engine","TArray_Add_Text",ICALL::API::TArray_Add_Text);
			CS_ICALL("Unreal.Core.Engine","TArray_Add_Color",ICALL::API::TArray_Add_Color);
			CS_ICALL("Unreal.Core.Engine","TArray_Add_Vector2D",ICALL::API::TArray_Add_Vector2D);
			CS_ICALL("Unreal.Core.Engine","TArray_Add_Vector3D",ICALL::API::TArray_Add_Vector3D);
			CS_ICALL("Unreal.Core.Engine","TArray_Add_Rotator",ICALL::API::TArray_Add_Rotator);
			CS_ICALL("Unreal.Core.Engine","TArray_Add_Transform",ICALL::API::TArray_Add_Transform);
			CS_ICALL("Unreal.Core.Engine","TArray_Add_Class",ICALL::API::TArray_Add_Class);
			CS_ICALL("Unreal.Core.Engine","TArray_Add_Object",ICALL::API::TArray_Add_Object);
			CS_ICALL("Unreal.Core.Engine","TArray_Add_Actor",ICALL::API::TArray_Add_Actor);
			CS_ICALL("Unreal.Core.Engine","TArray_Add_Component",ICALL::API::TArray_Add_Component);
			//
			CS_ICALL("Unreal.Core.Engine","TArray_Contains_Bool",ICALL::API::TArray_Contains_Bool);
			CS_ICALL("Unreal.Core.Engine","TArray_Contains_Byte",ICALL::API::TArray_Contains_Byte);
			CS_ICALL("Unreal.Core.Engine","TArray_Contains_Int",ICALL::API::TArray_Contains_Int);
			CS_ICALL("Unreal.Core.Engine","TArray_Contains_Int64",ICALL::API::TArray_Contains_Int64);
			CS_ICALL("Unreal.Core.Engine","TArray_Contains_Float",ICALL::API::TArray_Contains_Float);
			CS_ICALL("Unreal.Core.Engine","TArray_Contains_String",ICALL::API::TArray_Contains_String);
			CS_ICALL("Unreal.Core.Engine","TArray_Contains_Name",ICALL::API::TArray_Contains_Name);
			CS_ICALL("Unreal.Core.Engine","TArray_Contains_Text",ICALL::API::TArray_Contains_Text);
			CS_ICALL("Unreal.Core.Engine","TArray_Contains_Color",ICALL::API::TArray_Contains_Color);
			CS_ICALL("Unreal.Core.Engine","TArray_Contains_Vector2D",ICALL::API::TArray_Contains_Vector2D);
			CS_ICALL("Unreal.Core.Engine","TArray_Contains_Vector3D",ICALL::API::TArray_Contains_Vector3D);
			CS_ICALL("Unreal.Core.Engine","TArray_Contains_Rotator",ICALL::API::TArray_Contains_Rotator);
			CS_ICALL("Unreal.Core.Engine","TArray_Contains_Transform",ICALL::API::TArray_Contains_Transform);
			CS_ICALL("Unreal.Core.Engine","TArray_Contains_Class",ICALL::API::TArray_Contains_Class);
			CS_ICALL("Unreal.Core.Engine","TArray_Contains_Object",ICALL::API::TArray_Contains_Object);
			CS_ICALL("Unreal.Core.Engine","TArray_Contains_Actor",ICALL::API::TArray_Contains_Actor);
			CS_ICALL("Unreal.Core.Engine","TArray_Contains_Component",ICALL::API::TArray_Contains_Component);
			//
			CS_ICALL("Unreal.Core.Engine","TArray_FindItem_Bool",ICALL::API::TArray_FindItem_Bool);
			CS_ICALL("Unreal.Core.Engine","TArray_FindItem_Byte",ICALL::API::TArray_FindItem_Byte);
			CS_ICALL("Unreal.Core.Engine","TArray_FindItem_Int",ICALL::API::TArray_FindItem_Int);
			CS_ICALL("Unreal.Core.Engine","TArray_FindItem_Int64",ICALL::API::TArray_FindItem_Int64);
			CS_ICALL("Unreal.Core.Engine","TArray_FindItem_Float",ICALL::API::TArray_FindItem_Float);
			CS_ICALL("Unreal.Core.Engine","TArray_FindItem_String",ICALL::API::TArray_FindItem_String);
			CS_ICALL("Unreal.Core.Engine","TArray_FindItem_Name",ICALL::API::TArray_FindItem_Name);
			CS_ICALL("Unreal.Core.Engine","TArray_FindItem_Text",ICALL::API::TArray_FindItem_Text);
			CS_ICALL("Unreal.Core.Engine","TArray_FindItem_Color",ICALL::API::TArray_FindItem_Color);
			CS_ICALL("Unreal.Core.Engine","TArray_FindItem_Vector2D",ICALL::API::TArray_FindItem_Vector2D);
			CS_ICALL("Unreal.Core.Engine","TArray_FindItem_Vector3D",ICALL::API::TArray_FindItem_Vector3D);
			CS_ICALL("Unreal.Core.Engine","TArray_FindItem_Rotator",ICALL::API::TArray_FindItem_Rotator);
			CS_ICALL("Unreal.Core.Engine","TArray_FindItem_Transform",ICALL::API::TArray_FindItem_Transform);
			CS_ICALL("Unreal.Core.Engine","TArray_FindItem_Class",ICALL::API::TArray_FindItem_Class);
			CS_ICALL("Unreal.Core.Engine","TArray_FindItem_Object",ICALL::API::TArray_FindItem_Object);
			CS_ICALL("Unreal.Core.Engine","TArray_FindItem_Actor",ICALL::API::TArray_FindItem_Actor);
			CS_ICALL("Unreal.Core.Engine","TArray_FindItem_Component",ICALL::API::TArray_FindItem_Component);
			//
			CS_ICALL("Unreal.Core.Engine","TArray_RemoveItem_Bool",ICALL::API::TArray_RemoveItem_Bool);
			CS_ICALL("Unreal.Core.Engine","TArray_RemoveItem_Byte",ICALL::API::TArray_RemoveItem_Byte);
			CS_ICALL("Unreal.Core.Engine","TArray_RemoveItem_Int",ICALL::API::TArray_RemoveItem_Int);
			CS_ICALL("Unreal.Core.Engine","TArray_RemoveItem_Int64",ICALL::API::TArray_RemoveItem_Int64);
			CS_ICALL("Unreal.Core.Engine","TArray_RemoveItem_Float",ICALL::API::TArray_RemoveItem_Float);
			CS_ICALL("Unreal.Core.Engine","TArray_RemoveItem_String",ICALL::API::TArray_RemoveItem_String);
			CS_ICALL("Unreal.Core.Engine","TArray_RemoveItem_Name",ICALL::API::TArray_RemoveItem_Name);
			CS_ICALL("Unreal.Core.Engine","TArray_RemoveItem_Text",ICALL::API::TArray_RemoveItem_Text);
			CS_ICALL("Unreal.Core.Engine","TArray_RemoveItem_Color",ICALL::API::TArray_RemoveItem_Color);
			CS_ICALL("Unreal.Core.Engine","TArray_RemoveItem_Vector2D",ICALL::API::TArray_RemoveItem_Vector2D);
			CS_ICALL("Unreal.Core.Engine","TArray_RemoveItem_Vector3D",ICALL::API::TArray_RemoveItem_Vector3D);
			CS_ICALL("Unreal.Core.Engine","TArray_RemoveItem_Rotator",ICALL::API::TArray_RemoveItem_Rotator);
			CS_ICALL("Unreal.Core.Engine","TArray_RemoveItem_Transform",ICALL::API::TArray_RemoveItem_Transform);
			CS_ICALL("Unreal.Core.Engine","TArray_RemoveItem_Class",ICALL::API::TArray_RemoveItem_Class);
			CS_ICALL("Unreal.Core.Engine","TArray_RemoveItem_Object",ICALL::API::TArray_RemoveItem_Object);
			CS_ICALL("Unreal.Core.Engine","TArray_RemoveItem_Actor",ICALL::API::TArray_RemoveItem_Actor);
			CS_ICALL("Unreal.Core.Engine","TArray_RemoveItem_Component",ICALL::API::TArray_RemoveItem_Component);
		}
		// :: TSet.cs ::
		{
			CS_ICALL("Unreal.Core.Engine","TSet_Append",ICALL::API::TSet_Append);
			CS_ICALL("Unreal.Core.Engine","TSet_Clear",ICALL::API::TSet_Clear);
			CS_ICALL("Unreal.Core.Engine","TSet_Length",ICALL::API::TSet_Length);
			CS_ICALL("Unreal.Core.Engine","TSet_ToArray",ICALL::API::TSet_ToArray);
			//
			CS_ICALL("Unreal.Core.Engine","TSet_Add_Byte",ICALL::API::TSet_Add_Byte);
			CS_ICALL("Unreal.Core.Engine","TSet_Add_Int",ICALL::API::TSet_Add_Int);
			CS_ICALL("Unreal.Core.Engine","TSet_Add_Int64",ICALL::API::TSet_Add_Int64);
			CS_ICALL("Unreal.Core.Engine","TSet_Add_Float",ICALL::API::TSet_Add_Float);
			CS_ICALL("Unreal.Core.Engine","TSet_Add_String",ICALL::API::TSet_Add_String);
			CS_ICALL("Unreal.Core.Engine","TSet_Add_Name",ICALL::API::TSet_Add_Name);
			CS_ICALL("Unreal.Core.Engine","TSet_Add_Color",ICALL::API::TSet_Add_Color);
			CS_ICALL("Unreal.Core.Engine","TSet_Add_Vector2D",ICALL::API::TSet_Add_Vector2D);
			CS_ICALL("Unreal.Core.Engine","TSet_Add_Vector3D",ICALL::API::TSet_Add_Vector3D);
			CS_ICALL("Unreal.Core.Engine","TSet_Add_Class",ICALL::API::TSet_Add_Class);
			CS_ICALL("Unreal.Core.Engine","TSet_Add_Object",ICALL::API::TSet_Add_Object);
			CS_ICALL("Unreal.Core.Engine","TSet_Add_Actor",ICALL::API::TSet_Add_Actor);
			CS_ICALL("Unreal.Core.Engine","TSet_Add_Component",ICALL::API::TSet_Add_Component);
			//
			CS_ICALL("Unreal.Core.Engine","TSet_Contains_Byte",ICALL::API::TSet_Contains_Byte);
			CS_ICALL("Unreal.Core.Engine","TSet_Contains_Int",ICALL::API::TSet_Contains_Int);
			CS_ICALL("Unreal.Core.Engine","TSet_Contains_Int64",ICALL::API::TSet_Contains_Int64);
			CS_ICALL("Unreal.Core.Engine","TSet_Contains_Float",ICALL::API::TSet_Contains_Float);
			CS_ICALL("Unreal.Core.Engine","TSet_Contains_String",ICALL::API::TSet_Contains_String);
			CS_ICALL("Unreal.Core.Engine","TSet_Contains_Name",ICALL::API::TSet_Contains_Name);
			CS_ICALL("Unreal.Core.Engine","TSet_Contains_Color",ICALL::API::TSet_Contains_Color);
			CS_ICALL("Unreal.Core.Engine","TSet_Contains_Vector2D",ICALL::API::TSet_Contains_Vector2D);
			CS_ICALL("Unreal.Core.Engine","TSet_Contains_Vector3D",ICALL::API::TSet_Contains_Vector3D);
			CS_ICALL("Unreal.Core.Engine","TSet_Contains_Class",ICALL::API::TSet_Contains_Class);
			CS_ICALL("Unreal.Core.Engine","TSet_Contains_Object",ICALL::API::TSet_Contains_Object);
			CS_ICALL("Unreal.Core.Engine","TSet_Contains_Actor",ICALL::API::TSet_Contains_Actor);
			CS_ICALL("Unreal.Core.Engine","TSet_Contains_Component",ICALL::API::TSet_Contains_Component);
			//
			CS_ICALL("Unreal.Core.Engine","TSet_RemoveItem_Byte",ICALL::API::TSet_RemoveItem_Byte);
			CS_ICALL("Unreal.Core.Engine","TSet_RemoveItem_Int",ICALL::API::TSet_RemoveItem_Int);
			CS_ICALL("Unreal.Core.Engine","TSet_RemoveItem_Int64",ICALL::API::TSet_RemoveItem_Int64);
			CS_ICALL("Unreal.Core.Engine","TSet_RemoveItem_Float",ICALL::API::TSet_RemoveItem_Float);
			CS_ICALL("Unreal.Core.Engine","TSet_RemoveItem_String",ICALL::API::TSet_RemoveItem_String);
			CS_ICALL("Unreal.Core.Engine","TSet_RemoveItem_Name",ICALL::API::TSet_RemoveItem_Name);
			CS_ICALL("Unreal.Core.Engine","TSet_RemoveItem_Color",ICALL::API::TSet_RemoveItem_Color);
			CS_ICALL("Unreal.Core.Engine","TSet_RemoveItem_Vector2D",ICALL::API::TSet_RemoveItem_Vector2D);
			CS_ICALL("Unreal.Core.Engine","TSet_RemoveItem_Vector3D",ICALL::API::TSet_RemoveItem_Vector3D);
			CS_ICALL("Unreal.Core.Engine","TSet_RemoveItem_Class",ICALL::API::TSet_RemoveItem_Class);
			CS_ICALL("Unreal.Core.Engine","TSet_RemoveItem_Object",ICALL::API::TSet_RemoveItem_Object);
			CS_ICALL("Unreal.Core.Engine","TSet_RemoveItem_Actor",ICALL::API::TSet_RemoveItem_Actor);
			CS_ICALL("Unreal.Core.Engine","TSet_RemoveItem_Component",ICALL::API::TSet_RemoveItem_Component);
		}
		// :: TMap.cs ::
		{
			
			CS_ICALL("Unreal.Core.Engine","TMap_Clear",ICALL::API::TMap_Clear);
			CS_ICALL("Unreal.Core.Engine","TMap_Length",ICALL::API::TMap_Length);
			CS_ICALL("Unreal.Core.Engine","TMap_Keys",ICALL::API::TMap_Keys);
			CS_ICALL("Unreal.Core.Engine","TMap_Values",ICALL::API::TMap_Values);
			//
			CS_ICALL("Unreal.Core.Engine","TMap_FindItem_Byte",ICALL::API::TMap_FindItem_Byte);
			CS_ICALL("Unreal.Core.Engine","TMap_FindItem_Int",ICALL::API::TMap_FindItem_Int);
			CS_ICALL("Unreal.Core.Engine","TMap_FindItem_Int64",ICALL::API::TMap_FindItem_Int64);
			CS_ICALL("Unreal.Core.Engine","TMap_FindItem_Float",ICALL::API::TMap_FindItem_Float);
			CS_ICALL("Unreal.Core.Engine","TMap_FindItem_String",ICALL::API::TMap_FindItem_String);
			CS_ICALL("Unreal.Core.Engine","TMap_FindItem_Name",ICALL::API::TMap_FindItem_Name);
			CS_ICALL("Unreal.Core.Engine","TMap_FindItem_Color",ICALL::API::TMap_FindItem_Color);
			CS_ICALL("Unreal.Core.Engine","TMap_FindItem_Vector2D",ICALL::API::TMap_FindItem_Vector2D);
			CS_ICALL("Unreal.Core.Engine","TMap_FindItem_Vector3D",ICALL::API::TMap_FindItem_Vector3D);
			CS_ICALL("Unreal.Core.Engine","TMap_FindItem_Class",ICALL::API::TMap_FindItem_Class);
			CS_ICALL("Unreal.Core.Engine","TMap_FindItem_Object",ICALL::API::TMap_FindItem_Object);
			CS_ICALL("Unreal.Core.Engine","TMap_FindItem_Actor",ICALL::API::TMap_FindItem_Actor);
			CS_ICALL("Unreal.Core.Engine","TMap_FindItem_Component",ICALL::API::TMap_FindItem_Component);
			//
			CS_ICALL("Unreal.Core.Engine","TMap_RemoveItem_Byte",ICALL::API::TMap_RemoveItem_Byte);
			CS_ICALL("Unreal.Core.Engine","TMap_RemoveItem_Int",ICALL::API::TMap_RemoveItem_Int);
			CS_ICALL("Unreal.Core.Engine","TMap_RemoveItem_Int64",ICALL::API::TMap_RemoveItem_Int64);
			CS_ICALL("Unreal.Core.Engine","TMap_RemoveItem_Float",ICALL::API::TMap_RemoveItem_Float);
			CS_ICALL("Unreal.Core.Engine","TMap_RemoveItem_String",ICALL::API::TMap_RemoveItem_String);
			CS_ICALL("Unreal.Core.Engine","TMap_RemoveItem_Name",ICALL::API::TMap_RemoveItem_Name);
			CS_ICALL("Unreal.Core.Engine","TMap_RemoveItem_Color",ICALL::API::TMap_RemoveItem_Color);
			CS_ICALL("Unreal.Core.Engine","TMap_RemoveItem_Vector2D",ICALL::API::TMap_RemoveItem_Vector2D);
			CS_ICALL("Unreal.Core.Engine","TMap_RemoveItem_Vector3D",ICALL::API::TMap_RemoveItem_Vector3D);
			CS_ICALL("Unreal.Core.Engine","TMap_RemoveItem_Class",ICALL::API::TMap_RemoveItem_Class);
			CS_ICALL("Unreal.Core.Engine","TMap_RemoveItem_Object",ICALL::API::TMap_RemoveItem_Object);
			CS_ICALL("Unreal.Core.Engine","TMap_RemoveItem_Actor",ICALL::API::TMap_RemoveItem_Actor);
			CS_ICALL("Unreal.Core.Engine","TMap_RemoveItem_Component",ICALL::API::TMap_RemoveItem_Component);
		}
	}///
};

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class IENGINE {
public:
	static void Register() {
		// :: EngineFramework.cs ::
		{
			CS_API("LoadObjectClass",ICALL::API::LoadObjectClass);
			CS_API("CreateNewObject",ICALL::API::CreateNewObject);
		}
	}
};

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////